CREATE TABLE dbo.Category(
	Id INT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Cateogory PRIMARY KEY,
	[Name] NVARCHAR(250),
	[Description] NVARCHAR(500),
	IsActive BIT NOT NULL CONSTRAINT DF_Category_IsActive DEFAULT (0)
);
GO

CREATE TABLE dbo.Product(
	Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Product PRIMARY KEY,
	[Name] NVARCHAR(250) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	Price DECIMAL(18,2) NOT NULL DEFAULT 0,
	StockQuantity INT NOT NULL DEFAULT 0, 
	CreatedDate DATETIME2 NOT NULL CONSTRAINT DF_Product_CreatedAt DEFAULT (GETUTCDATE()),
	IsActive BIT NOT NULL CONSTRAINT DF_Product_IsActive DEFAULT (0),
	CategoryId INT NOT NULL CONSTRAINT FK_Product_Category REFERENCES dbo.Category (Id)
);
GO

